# Generated by Django 5.0.4 on 2024-06-12 12:51

import films.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to=films.models.get_upload_to
            ),
        ),
    ]
