# Generated by Django 5.0.4 on 2024-06-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0002_alter_film_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="reviews_summary",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
