# Generated by Django 5.0.4 on 2024-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                max_length=100, null=False, blank=False, unique=True
            ),
        ),
    ]
