# Generated by Django 5.0.4 on 2024-06-12 12:51

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.get_upload_to
            ),
        ),
    ]
