version: '3.9'

networks:
  network_tfr:
    driver: bridge

volumes:
    tfr_postgres_data: {}

services:
  app:
    image: tfr_app
    container_name: tfr_app
    hostname: app
    build: .
    restart: unless-stopped
    tty: true
    volumes:
        - ./:/app/
    ports:
      - "8000:8000"
    networks:
      - network_tfr
    depends_on:
      - postgres
      - mailpit
    env_file: .env
    environment:
      DEBUG: true
      DATABASE_URL: psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    command: >
      bash -c "./start.sh
      && uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'"

  postgres:
    container_name: tfr_postgres
    image: postgres:16.3-bullseye
    restart: always
    networks:
        - network_tfr
    volumes:
        - tfr_postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      TZ: 'Asia/Bangkok'
      PGTZ: 'Asia/Bangkok'

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: tfr_mailpit
    ports:
      - "8025:8025"
    networks:
      - network_tfr
